In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('gene_high_throughput_sequencing.csv',sep=',')

In [3]:
data.head()

Patient_id Diagnosis  LOC643837  LOC100130417     SAMD11  \
0  STT5425_Breast_001_normal    normal   1.257614      2.408148  13.368622   
1  STT5427_Breast_023_normal    normal   4.567931     16.602734  42.477752   
2  STT5430_Breast_002_normal    normal   2.077597      3.978294  12.863214   
3  STT5439_Breast_003_normal    normal   2.066576      8.520713  14.466035   
4  STT5441_Breast_004_normal    normal   2.613616      3.434965  12.682222   

       NOC2L     KLHL17    PLEKHN1   C1orf170       HES4  ...      CLIC2  \
0   9.494779  20.880435  12.722017   9.494779  54.349694  ...   4.761250   
1  25.562376  23.221137  11.622386  14.330573  72.445474  ...   6.871902   
2  13.728915  14.543176  14.141907   6.232790  57.011005  ...   7.096343   
3   7.823932   8.520713   2.066576  10.870009  53.292034  ...   5.200770   
4  10.543189  26.688686  12.484822   1.364917  67.140393  ...  11.227770   

     RPS4Y1       ZFY      PRKY     USP9Y     DDX3Y       CD24  CYorf15B  \
0  1.257614  1.257614  1.257614  1.257614  1.257614  23.268694  1.257614   
1  1.815112  1.815112  1.815112  1.815112  1.815112  10.427023  1.815112   
2  2.077597  2.077597  2.077597  2.077597  2.077597  22.344226  2.077597   
3  2.066576  2.066576  2.066576  2.066576  2.066576  49.295538  2.066576   
4  1.364917  1.364917  1.364917  1.364917  1.364917  23.627911  1.364917   

      KDM5D    EIF1AY  
0  1.257614  1.257614  
1  1.815112  1.815112  
2  2.077597  2.077597  
3  2.066576  2.066576  
4  1.364917  1.364917  

[5 rows x 15750 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Columns: 15750 entries, Patient_id to EIF1AY
dtypes: float64(15748), object(2)
memory usage: 8.7+ MB


In [5]:
data['Diagnosis']

0     normal
1     normal
2     normal
3     normal
4     normal
       ...  
67    cancer
68    cancer
69    cancer
70    cancer
71    cancer
Name: Diagnosis, Length: 72, dtype: object

In [6]:
import scipy
from statsmodels.stats.weightstats import *

In [7]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [8]:
data.Diagnosis.value_counts()

early neoplasia    25
normal             24
cancer             23
Name: Diagnosis, dtype: int64

In [9]:
values_1=data.iloc[range(24), [2]]
values_2=data.iloc[range(24,49), [2]]
values_3=data.iloc[range(49,72), [2]]

In [10]:
values_3

LOC643837
49   1.618129
50   1.609022
51   1.549953
52   1.606786
53   2.697819
54   1.126738
55   3.163299
56   1.428276
57   2.604658
58   3.331313
59   1.802589
60   0.903290
61   5.990041
62   1.115085
63   3.746660
64   1.345676
65   0.989392
66   1.593890
67   1.466240
68   2.492410
69   3.530477
70   3.733734
71   0.833898

In [11]:
len(values_2)

25

In [12]:
arr1=list()
arr2=list()
for i in range(2,15750):
    values_1=data.iloc[range(24), [i]]
    values_2=data.iloc[range(24,49), [i]]
    values_3=data.iloc[range(49,72), [i]]
    stat,p1=scipy.stats.ttest_ind(values_1, values_2, equal_var=False)
    stat,p2=scipy.stats.ttest_ind(values_2, values_3, equal_var=False)
    arr1.append(p1[0])
    arr2.append(p2[0])

In [13]:
arr1[0]

0.6907660157497355

In [59]:
p

array([0.69076602])

In [16]:
with open("arr1.txt",'w',encoding = 'utf-8') as f:
    for index in arr1:
        f.write(str(index) + ',')
  

In [17]:
with open("arr2.txt",'w',encoding = 'utf-8') as f:
    for index in arr2:
        f.write(str(index) + ',')
  

In [18]:
ans1=0
ans2=0
for i in range(len(arr1)):
    if arr1[i]<=0.05:
        ans1+=1
    if arr2[i]<=0.05:
        ans2+=1

In [115]:
ans2

3490

In [60]:
data

Patient_id Diagnosis  LOC643837  LOC100130417     SAMD11  \
0   STT5425_Breast_001_normal    normal   1.257614      2.408148  13.368622   
1   STT5427_Breast_023_normal    normal   4.567931     16.602734  42.477752   
2   STT5430_Breast_002_normal    normal   2.077597      3.978294  12.863214   
3   STT5439_Breast_003_normal    normal   2.066576      8.520713  14.466035   
4   STT5441_Breast_004_normal    normal   2.613616      3.434965  12.682222   
..                        ...       ...        ...           ...        ...   
67    STT5750_Breast_021_DCIS    cancer   1.466240      3.689955  21.331981   
68     STT5751_Breast_021_IDC    cancer   2.492410     12.279444  30.087759   
69     STT5758_Breast_022_IDC    cancer   3.530477     20.006038  53.924651   
70     STT5763_Breast_022_IDC    cancer   3.733734      8.860505  32.538666   
71     STT5825_Breast_024_IDC    cancer   0.833898     18.084880  60.584449   

        NOC2L     KLHL17    PLEKHN1   C1orf170       HES4  ...      CLIC2  \
0    9.494779  20.880435  12.722017   9.494779  54.349694  ...   4.761250   
1   25.562376  23.221137  11.622386  14.330573  72.445474  ...   6.871902   
2   13.728915  14.543176  14.141907   6.232790  57.011005  ...   7.096343   
3    7.823932   8.520713   2.066576  10.870009  53.292034  ...   5.200770   
4   10.543189  26.688686  12.484822   1.364917  67.140393  ...  11.227770   
..        ...        ...        ...        ...        ...  ...        ...   
67  19.359546  23.505609  11.576176  11.325851  80.572057  ...   2.807635   
68  17.703926  26.064890  10.707081  11.520120  65.041865  ...   2.492410   
69  25.449565  30.949995  16.794696  17.121366  70.958462  ...   1.176826   
70  21.585069  24.987992  11.460224  11.201202  67.767125  ...   2.840946   
71  29.659104  31.093687  13.298860  11.010397  55.771485  ...   3.698096   

      RPS4Y1       ZFY      PRKY     USP9Y     DDX3Y       CD24  CYorf15B  \
0   1.257614  1.257614  1.257614  1.257614  1.257614  23.268694  1.257614   
1   1.815112  1.815112  1.815112  1.815112  1.815112  10.427023  1.815112   
2   2.077597  2.077597  2.077597  2.077597  2.077597  22.344226  2.077597   
3   2.066576  2.066576  2.066576  2.066576  2.066576  49.295538  2.066576   
4   1.364917  1.364917  1.364917  1.364917  1.364917  23.627911  1.364917   
..       ...       ...       ...       ...       ...        ...       ...   
67  1.466240  2.807635  1.466240  2.807635  3.689955  18.449777  1.466240   
68  2.492410  1.301619  3.275668  1.301619  1.301619   8.601194  1.301619   
69  1.176826  1.176826  2.961613  1.176826  1.176826  10.764365  1.176826   
70  1.483635  1.483635  1.483635  1.483635  1.483635   8.522837  1.483635   
71  1.596792  1.596792  3.698096  0.833898  0.833898  13.978672  0.833898   

       KDM5D    EIF1AY  
0   1.257614  1.257614  
1   1.815112  1.815112  
2   2.077597  2.077597  
3   2.066576  2.066576  
4   1.364917  1.364917  
..       ...       ...  
67  1.466240  1.466240  
68  1.301619  1.301619  
69  1.176826  1.176826  
70  1.483635  1.483635  
71  2.848303  0.833898  

[72 rows x 15750 columns]

# Chapater 2

In [21]:
from statsmodels.sandbox.stats.multicomp import multipletests 

In [63]:
reject, p_corrected1, a, a2 = multipletests(arr1, 
                                            alpha = 0.25, 
                                            method = 'bonferroni')# eto hernya

In [25]:
reject, p_corrected2, a1, a2 = multipletests(arr2, 
                                            alpha = 0.05, 
                                            method = 'bonferroni')#eto hernya

In [71]:
reject, p_corrected_1_holm, a1, a2 = multipletests(arr1, 
                                            alpha = 0.5, 
                                            method = 'holm') 

In [70]:
reject, p_corrected_2_holm, a1, a2 = multipletests(arr2, 
                                            alpha = 0.5, 
                                            method = 'holm') 

In [72]:
p_corrected_1_holm

array([1.        , 0.50017368, 1.        , ..., 1.        , 1.        ,
       1.        ])

In [78]:
ans3=0
ans4=0
for i in range(len(p_corrected_1_holm)):
    if p_corrected_1_holm[i]<=0.025:
        ans3+=1
        
    if p_corrected_2_holm[i]<=0.025:
        ans4+=1

In [79]:
ans4

79

In [77]:
p_corrected1

array([1.        , 0.50055511, 1.        , ..., 1.        , 1.        ,
       1.        ])

In [76]:
def fold_change(C,T):
    if T>C:
        return T/C
    else: return -C/T

In [80]:
val_mean1 = list()
val_mean2 = list()
val_mean3 = list()
for i in range(2,15750):
    values_1=data.iloc[range(24), [i]]
    val_mean1.append(values_1.mean())
    values_2=data.iloc[range(24,49), [i]]
    values_3=data.iloc[range(49,72), [i]]
    val_mean2.append(values_2.mean())
    val_mean3.append(values_3.mean())

In [105]:
ans3=0
ans4=0
for i in range(len(p_corrected_1_holm)):
    if p_corrected_1_holm[i]<=0.025:
        
        if abs(fold_change(val_mean1[i][0],val_mean2[i][0]))>1.5:
            ans3+=1
    if p_corrected_2_holm[i]<=0.025:
        
        if abs(fold_change(val_mean2[i][0],val_mean3[i][0]))>1.5:
            ans4+=1

In [106]:
len(val_mean1)

15748

In [108]:
ans3

2

In [109]:
ans4

77

In [96]:
len(p_corrected_1_holm)

15748

# Task3

In [110]:
reject, p_corrected_1_fdr_bh, a1, a2 = multipletests(arr1, 
                                            alpha = 0.5, 
                                            method = 'fdr_bh') 
reject, p_corrected_2_fdr_bh, a1, a2 = multipletests(arr2, 
                                            alpha = 0.5, 
                                            method = 'fdr_bh') 

In [111]:
ans5=0
ans6=0
for i in range(len(p_corrected_1_fdr_bh)):
    if p_corrected_1_fdr_bh[i]<=0.025:
        
        if abs(fold_change(val_mean1[i][0],val_mean2[i][0]))>1.5:
            ans5+=1
    if p_corrected_2_fdr_bh[i]<=0.025:
        
        if abs(fold_change(val_mean2[i][0],val_mean3[i][0]))>1.5:
            ans6+=1

In [112]:
ans5

4

In [113]:
ans6

524