In [2]:
import numpy as np
import cv2



In [30]:
img1 = cv2.imread('lenna.jpg')
img = cv2.imread('img.jpg')


In [4]:
print(img1)

[[[ 59 103 157]
  [ 60 104 158]
  [ 61 105 159]
  ...
  [  8  32  56]
  [  5  28  54]
  [  8  31  57]]

 [[ 59 103 157]
  [ 60 104 158]
  [ 61 105 159]
  ...
  [  8  32  56]
  [  4  27  53]
  [  7  30  56]]

 [[ 60 104 158]
  [ 61 105 159]
  [ 61 105 159]
  ...
  [  9  33  57]
  [  7  30  56]
  [ 10  33  59]]

 ...

 [[  9  31  56]
  [  8  30  55]
  [  8  30  55]
  ...
  [ 47  74 118]
  [ 45  72 116]
  [ 44  71 115]]

 [[  9  32  58]
  [  7  31  55]
  [  8  30  55]
  ...
  [ 47  74 118]
  [ 46  73 117]
  [ 46  73 117]]

 [[ 13  36  62]
  [  9  32  58]
  [  8  30  55]
  ...
  [ 45  72 116]
  [ 47  74 118]
  [ 49  76 120]]]


In [25]:

kernel = np.array([[1,0,-1],[1,0,-1],[1,0,-1]],np.float32) / 9
dst = cv2.filter2D(img1,-1,kernel)

In [26]:
#Отображение файла встроенными средствами OpenCV. 
cv2.imshow("Original image", dst) #
cv2.waitKey(0) # Ждем нажатия любой клавиши

-1

In [8]:
print('j')

j


In [35]:
equ = cv2.equalizeHist(img)


In [37]:
cv2.generate_histogram(img)

AttributeError: module 'cv2.cv2' has no attribute 'generate_histogram'