# pretest

In [2]:
import pandas as pd
data = pd.read_csv('illiteracy.txt', sep = '\t', header = 0)

In [3]:
data.head()

Country  Illit  Births
0  Albania   20.5    1.78
1  Algeria   39.1    2.44
2  Bahrain   15.0    2.34
3   Belize    5.9    2.97
4    Benin   73.5    5.60

In [4]:
rer = data[['Illit','Births']]
correlation = rer.corr()

In [5]:
correlation

Illit    Births
Illit   1.000000  0.768663
Births  0.768663  1.000000

In [6]:
 rer.corr(method='spearman')

Illit    Births
Illit   1.000000  0.752962
Births  0.752962  1.000000

# Test

In [7]:
data = pd.read_csv('water.txt', sep = '\t', header = 0)

In [8]:
data.head()

location        town  mortality  hardness
0    South        Bath       1247       105
1    North  Birkenhead       1668        17
2    South  Birmingham       1466         5
3    North   Blackburn       1800        14
4    North   Blackpool       1609        18

In [12]:
rer = data[['hardness','mortality']]
correlation = rer.corr()

In [13]:
correlation

hardness  mortality
hardness   1.000000  -0.654849
mortality -0.654849   1.000000

In [14]:
rer.corr(method='spearman')

hardness  mortality
hardness   1.000000  -0.631665
mortality -0.631665   1.000000

In [16]:
data_s=data[data.location=='South']
rer_s = data_s[['hardness','mortality']]
correlation_s = rer_s.corr()

In [19]:
data_n=data[data.location=='North']
rer_n = data_n[['hardness','mortality']]
correlation_n = rer_n.corr()

In [20]:
correlation_s

hardness  mortality
hardness   1.000000  -0.602153
mortality -0.602153   1.000000

In [22]:
correlation_n

hardness  mortality
hardness   1.000000  -0.368598
mortality -0.368598   1.000000

In [25]:
def matthews_correlation(a,b,c,d):
    chis = a*d-b*c
    znam = (a+b)*(a+c)*(b+d)*(c+d)
    return chis/(znam**0.5)

In [26]:
a = 203
c = 718
b = 239
d = 515
print matthews_correlation(a,b,c,d)

-0.109002374587


In [31]:
import numpy as np
from scipy.stats import chi2_contingency
obs = np.array([[203,239], [718,515]])
print chi2_contingency(obs)

(19.40753078854304, 1.0558987006638725e-05, 1L, array([[243.03402985, 198.96597015],
       [677.96597015, 555.03402985]]))


In [30]:
obs

array([[203, 239],
       [718, 515]])

In [32]:
def proportions_diff_confint_ind(sample1, sample2, alpha = 0.05):    
    z = scipy.stats.norm.ppf(1 - alpha / 2.)
    
    p1 = float(sum(sample1)) / len(sample1)
    p2 = float(sum(sample2)) / len(sample2)
    
    left_boundary = (p1 - p2) - z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    right_boundary = (p1 - p2) + z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    
    return (left_boundary, right_boundary)
def proportions_diff_z_stat_ind(sample1, sample2):
    n1 = len(sample1)
    n2 = len(sample2)
    
    p1 = float(sum(sample1)) / n1
    p2 = float(sum(sample2)) / n2 
    P = float(p1*n1 + p2*n2) / (n1 + n2)
    
    return (p1 - p2) / np.sqrt(P * (1 - P) * (1. / n1 + 1. / n2))
def proportions_diff_z_test(z_stat, alternative = 'two-sided'):
    if alternative not in ('two-sided', 'less', 'greater'):
        raise ValueError("alternative not recognized\n"
                         "should be 'two-sided', 'less' or 'greater'")
    
    if alternative == 'two-sided':
        return 2 * (1 - scipy.stats.norm.cdf(np.abs(z_stat)))
    
    if alternative == 'less':
        return scipy.stats.norm.cdf(z_stat)

    if alternative == 'greater':
        return 1 - scipy.stats.norm.cdf(z_stat)

In [33]:
a = [1]*203+[0]*718
b = [1]*239+[0]*515

In [36]:
import scipy
print "95%% confidence interval for a difference between proportions: [%f, %f]" %\
      proportions_diff_confint_ind(b, a)

95% confidence interval for a difference between proportions: [0.053905, 0.139222]


In [37]:
print "p-value: %f" % proportions_diff_z_test(proportions_diff_z_stat_ind(a, b))

p-value: 0.000008


# №8

In [38]:
obs = np.array([[197,111,33],[382,685,331],[110,342,333]])

In [39]:
obs

array([[197, 111,  33],
       [382, 685, 331],
       [110, 342, 333]])

In [40]:
import numpy as np
import pandas as pd

from scipy import stats

In [ ]:
stats.chisquare(observed_frequences, expected_frequences, ddof = 1)

In [42]:
stats.chi2_contingency(obs)

(293.68311039689746,
 2.4964299580093467e-62,
 4L,
 array([[ 93.08597464, 153.74722662,  94.16679873],
        [381.6251981 , 630.318542  , 386.0562599 ],
        [214.28882726, 353.93423138, 216.77694136]]))

# №9

In [47]:
p= 2.4964299580093467e-62

# №10

In [43]:
197+111+33+382+685+331+110+342+333

2524

In [44]:
a = 293.68311039689746

In [45]:
v=(a/(2524*2))**0.5

In [46]:
v

0.2412013934500338

# Test

In [1]:
import pandas as pd
data = pd.read_csv('AUCs.txt', sep = '\t', header = 0)

In [2]:
data.head()

Unnamed: 0   C4.5  C4.5+m  C4.5+cf  C4.5+m+cf
0           adult (sample)  0.763   0.768    0.771      0.798
1            breast cancer  0.599   0.591    0.590      0.569
2  breast cancer wisconsin  0.954   0.971    0.968      0.967
3                      cmc  0.628   0.661    0.654      0.657
4               ionosphere  0.882   0.888    0.886      0.898

In [31]:
import numpy as np
import pandas as pd
import itertools
stat=list()
pval=list()
from scipy import stats
from statsmodels.stats.descriptivestats import sign_test
from statsmodels.stats.weightstats import zconfint
a = ['C4.5','C4.5','C4.5','C4.5+m','C4.5+m','C4.5+cf']
b = ['C4.5+m','C4.5+cf','C4.5+m+cf','C4.5+cf','C4.5+m+cf','C4.5+m+cf']
for i in range(6):
    print a[i],b[i],stats.wilcoxon(data[a[i]], data[b[i]])
    c,s=stats.wilcoxon(data[a[i]], data[b[i]])
    stat.append(c)
    pval.append(s)

C4.5 C4.5+m WilcoxonResult(statistic=6.5, pvalue=0.01075713311978963)
C4.5 C4.5+cf WilcoxonResult(statistic=43.0, pvalue=0.861262330095348)
C4.5 C4.5+m+cf WilcoxonResult(statistic=11.0, pvalue=0.015906444101703374)
C4.5+m C4.5+cf WilcoxonResult(statistic=17.0, pvalue=0.046332729793395394)
C4.5+m C4.5+m+cf WilcoxonResult(statistic=22.0, pvalue=0.3278256758446406)
C4.5+cf C4.5+m+cf WilcoxonResult(statistic=10.0, pvalue=0.022909099354356588)


In [32]:
frame = pd.DataFrame({'A':['C4.5','C4.5','C4.5','C4.5+m','C4.5+m','C4.5+cf',], 'B':['C4.5+m','C4.5+cf','C4.5+m+cf','C4.5+cf','C4.5+m+cf','C4.5+m+cf',],'stat':stat, 'p':pval})

In [33]:
frame

A          B         p  stat
0     C4.5     C4.5+m  0.010757   6.5
1     C4.5    C4.5+cf  0.861262  43.0
2     C4.5  C4.5+m+cf  0.015906  11.0
3   C4.5+m    C4.5+cf  0.046333  17.0
4   C4.5+m  C4.5+m+cf  0.327826  22.0
5  C4.5+cf  C4.5+m+cf  0.022909  10.0

In [38]:
reject, p_corrected, a1, a2 = multipletests(frame.p, 
                                            alpha = 0.05, 
                                            method = 'holm') 
frame['p_corrected'] = p_corrected
frame['reject'] = reject

In [39]:
frame

A          B         p  stat  p_corrected  reject
0     C4.5     C4.5+m  0.010757   6.5     0.064543   False
1     C4.5    C4.5+cf  0.861262  43.0     0.861262   False
2     C4.5  C4.5+m+cf  0.015906  11.0     0.079532   False
3   C4.5+m    C4.5+cf  0.046333  17.0     0.138998   False
4   C4.5+m  C4.5+m+cf  0.327826  22.0     0.655651   False
5  C4.5+cf  C4.5+m+cf  0.022909  10.0     0.091636   False